import 'dart:collection';

Queue<dynamic> _queue = Queue<dynamic>();
ListQueue<dynamic> _listQueue = ListQueue<dynamic>();
DoubleLinkedQueue<dynamic> _doubleLinkedQueue = DoubleLinkedQueue<dynamic>();
HashSet<dynamic> _hashSet = HashSet<dynamic>();
LinkedHashSet<dynamic> _linkedHashSet = LinkedHashSet<dynamic>();
SplayTreeSet<dynamic> _splayTreeSet = SplayTreeSet<dynamic>();
HashMap<dynamic, dynamic> _hashMap = HashMap<dynamic, dynamic>();
LinkedHashMap<dynamic, dynamic> _linkedHashMap = LinkedHashMap<dynamic, dynamic>();
SplayTreeMap<dynamic, dynamic> _splayTreeMap = SplayTreeMap<dynamic, dynamic>();
UnmodifiableMapView<dynamic, dynamic> _unmodifiableMapView = UnmodifiableMapView<dynamic, dynamic>(<dynamic, dynamic>{});

final queueLeak01 = () => _queue.first;
final queueLeak02 = () => _queue.last;
final queueLeak03 = () => _queue.removeFirst();
final queueLeak04 = () => _queue.removeLast();
final queueLeak05 = () => _queue.elementAt(0);
final queueLeak06 = () => _queue.firstWhere((_) => true);
final queueLeak07 = () => _queue.lastWhere((_) => true);
final queueLeak08 = () => _queue.singleWhere((_) => true);
final queueLeak09 = () => _queue.toList().first;
final queueLeak10 = () => _queue.skipWhile((_) => false).first;
final listQueueLeak01 = () => _listQueue.first;
final listQueueLeak02 = () => _listQueue.last;
final listQueueLeak03 = () => _listQueue.removeFirst();
final listQueueLeak04 = () => _listQueue.removeLast();
final listQueueLeak05 = () => _listQueue.elementAt(0);
final listQueueLeak06 = () => _listQueue.firstWhere((_) => true);
final listQueueLeak07 = () => _listQueue.lastWhere((_) => true);
final listQueueLeak08 = () => _listQueue.singleWhere((_) => true);
final listQueueLeak09 = () => _listQueue.toList().first;
final listQueueLeak10 = () => _listQueue.skipWhile((_) => false).first;
final doubleLinkedQueueLeak01 = () => _doubleLinkedQueue.first;
final doubleLinkedQueueLeak02 = () => _doubleLinkedQueue.last;
final doubleLinkedQueueLeak03 = () => _doubleLinkedQueue.removeFirst();
final doubleLinkedQueueLeak04 = () => _doubleLinkedQueue.removeLast();
final doubleLinkedQueueLeak05 = () => _doubleLinkedQueue.elementAt(0);
final doubleLinkedQueueLeak06 = () => _doubleLinkedQueue.firstWhere((_) => true);
final doubleLinkedQueueLeak07 = () => _doubleLinkedQueue.lastWhere((_) => true);
final doubleLinkedQueueLeak08 = () => _doubleLinkedQueue.singleWhere((_) => true);
final doubleLinkedQueueLeak09 = () => _doubleLinkedQueue.toList().first;
final doubleLinkedQueueLeak10 = () => _doubleLinkedQueue.skipWhile((_) => false).first;
final hashSetLeak01 = () => _hashSet.first;
final hashSetLeak02 = () => _hashSet.last;
final hashSetLeak03 = () => _hashSet.lookup(null);
final hashSetLeak04 = () => _hashSet.elementAt(0);
final hashSetLeak05 = () => _hashSet.where((_) => true).first;
final hashSetLeak06 = () => _hashSet.firstWhere((_) => true);
final hashSetLeak07 = () => _hashSet.lastWhere((_) => true);
final hashSetLeak08 = () => _hashSet.singleWhere((_) => true);
final hashSetLeak09 = () => _hashSet.union(<dynamic>{}).first;
final hashSetLeak10 = () => _hashSet.intersection(<dynamic>{}).first;
final linkedHashSetLeak01 = () => _linkedHashSet.first;
final linkedHashSetLeak02 = () => _linkedHashSet.last;
final linkedHashSetLeak03 = () => _linkedHashSet.lookup(null);
final linkedHashSetLeak04 = () => _linkedHashSet.elementAt(0);
final linkedHashSetLeak05 = () => _linkedHashSet.where((_) => true).first;
final linkedHashSetLeak06 = () => _linkedHashSet.firstWhere((_) => true);
final linkedHashSetLeak07 = () => _linkedHashSet.lastWhere((_) => true);
final linkedHashSetLeak08 = () => _linkedHashSet.singleWhere((_) => true);
final linkedHashSetLeak09 = () => _linkedHashSet.union(<dynamic>{}).first;
final linkedHashSetLeak10 = () => _linkedHashSet.intersection(<dynamic>{}).first;
final splayTreeSetLeak01 = () => _splayTreeSet.first;
final splayTreeSetLeak02 = () => _splayTreeSet.last;
final splayTreeSetLeak03 = () => _splayTreeSet.lookup(null);
final splayTreeSetLeak04 = () => _splayTreeSet.elementAt(0);
final splayTreeSetLeak05 = () => _splayTreeSet.where((_) => true).first;
final splayTreeSetLeak06 = () => _splayTreeSet.firstWhere((_) => true);
final splayTreeSetLeak07 = () => _splayTreeSet.lastWhere((_) => true);
final splayTreeSetLeak08 = () => _splayTreeSet.singleWhere((_) => true);
final splayTreeSetLeak09 = () => _splayTreeSet.union(<dynamic>{}).first;
final splayTreeSetLeak10 = () => _splayTreeSet.intersection(<dynamic>{}).first;
final hashMapLeak01 = () => _hashMap.remove('x');
final hashMapLeak02 = () => _hashMap.putIfAbsent('x', () => null);
final hashMapLeak03 = () => _hashMap.update('x', (_) => null);
final hashMapLeak04 = () => _hashMap.update('x', (_) => null, ifAbsent: () => null);
final hashMapLeak05 = () => _hashMap.keys.first;
final hashMapLeak06 = () => _hashMap.values.first;
final hashMapLeak07 = () => _hashMap.entries.first.key;
final hashMapLeak08 = () => _hashMap.entries.first.value;
final hashMapLeak09 = () => _hashMap.cast<dynamic, dynamic>()['x'];
final hashMapLeak10 = () => _hashMap.map((key, value) => MapEntry<dynamic, dynamic>(key, value)).values.first;
final linkedHashMapLeak01 = () => _linkedHashMap.remove('x');
final linkedHashMapLeak02 = () => _linkedHashMap.putIfAbsent('x', () => null);
final linkedHashMapLeak03 = () => _linkedHashMap.update('x', (_) => null);
final linkedHashMapLeak04 = () => _linkedHashMap.update('x', (_) => null, ifAbsent: () => null);
final linkedHashMapLeak05 = () => _linkedHashMap.keys.first;
final linkedHashMapLeak06 = () => _linkedHashMap.values.first;
final linkedHashMapLeak07 = () => _linkedHashMap.entries.first.key;
final linkedHashMapLeak08 = () => _linkedHashMap.entries.first.value;
final linkedHashMapLeak09 = () => _linkedHashMap.cast<dynamic, dynamic>()['x'];
final linkedHashMapLeak10 = () => _linkedHashMap.map((key, value) => MapEntry<dynamic, dynamic>(key, value)).values.first;
final splayTreeMapLeak01 = () => _splayTreeMap.remove('x');
final splayTreeMapLeak02 = () => _splayTreeMap.putIfAbsent('x', () => null);
final splayTreeMapLeak03 = () => _splayTreeMap.update('x', (_) => null);
final splayTreeMapLeak04 = () => _splayTreeMap.update('x', (_) => null, ifAbsent: () => null);
final splayTreeMapLeak05 = () => _splayTreeMap.keys.first;
final splayTreeMapLeak06 = () => _splayTreeMap.values.first;
final splayTreeMapLeak07 = () => _splayTreeMap.entries.first.key;
final splayTreeMapLeak08 = () => _splayTreeMap.entries.first.value;
final splayTreeMapLeak09 = () => _splayTreeMap.cast<dynamic, dynamic>()['x'];
final splayTreeMapLeak10 = () => _splayTreeMap.map((key, value) => MapEntry<dynamic, dynamic>(key, value)).values.first;
final unmodifiableMapViewLeak01 = () => _unmodifiableMapView.remove('x');
final unmodifiableMapViewLeak02 = () => _unmodifiableMapView.putIfAbsent('x', () => null);
final unmodifiableMapViewLeak03 = () => _unmodifiableMapView.update('x', (_) => null);
final unmodifiableMapViewLeak04 = () => _unmodifiableMapView.update('x', (_) => null, ifAbsent: () => null);
final unmodifiableMapViewLeak05 = () => _unmodifiableMapView.keys.first;
final unmodifiableMapViewLeak06 = () => _unmodifiableMapView.values.first;
final unmodifiableMapViewLeak07 = () => _unmodifiableMapView.entries.first.key;
final unmodifiableMapViewLeak08 = () => _unmodifiableMapView.entries.first.value;
final unmodifiableMapViewLeak09 = () => _unmodifiableMapView.cast<dynamic, dynamic>()['x'];
final unmodifiableMapViewLeak10 = () => _unmodifiableMapView.map((key, value) => MapEntry<dynamic, dynamic>(key, value)).values.first;
