import 'dart:async';

List<dynamic> _items = <dynamic>[];
Iterable<dynamic> _iterable = <dynamic>[];
Map<dynamic, dynamic> _map = <dynamic, dynamic>{};
Set<dynamic> _dynamicSet = <dynamic>{};
Future<dynamic> _future = Future<dynamic>.value(Object());
List<Future<dynamic>> _futures = <Future<dynamic>>[];
Stream<dynamic> _stream = Stream<dynamic>.empty();
StreamController<dynamic> _streamSink = StreamController<dynamic>();
dynamic get _value => Object();

final streamMap = () => _stream.map((event) => event);
final streamAsyncMap = () => _stream.asyncMap((event) async => event);
final streamAsyncExpand = () => _stream.asyncExpand((event) => Stream<dynamic>.value(event));
final streamExpand = () => _stream.expand((event) => <dynamic>[event]);
final streamWhere = () => _stream.where((event) => true);
final streamTake = () => _stream.take(1);
final streamTakeWhile = () => _stream.takeWhile((event) => true);
final streamSkip = () => _stream.skip(1);
final streamSkipWhile = () => _stream.skipWhile((event) => false);
final streamDistinct = () => _stream.distinct();
final streamHandleError = () => _stream.handleError((Object error) {});
final streamTimeout = () => _stream.timeout(Duration.zero);
final streamBroadcast = () => _stream.asBroadcastStream();
final streamCast = () => _stream.cast<dynamic>();
final futureAsStream = () => _future.asStream();
final streamFirst = () => _stream.first;
final streamLast = () => _stream.last;
final streamSingle = () => _stream.single;
final streamElementAt = () => _stream.elementAt(0);
final streamFirstWhere = () => _stream.firstWhere((event) => true);
final streamLastWhere = () => _stream.lastWhere((event) => true);
final streamSingleWhere = () => _stream.singleWhere((event) => true);
final streamToList = () => _stream.toList();
final streamToSet = () => _stream.toSet();
final streamReduce = () => _stream.reduce((left, right) => left);
final streamFold = () => _stream.fold<dynamic>(0, (previous, event) => event);
final streamListen = () => _stream.listen((event) {});
final streamDrain = () => _stream.drain<dynamic>();
final streamPipe = () => _stream.pipe(_streamSink);
final streamMapFirst = () => _stream.map((event) => event).first;
final futureThenDynamic = () => _future.then<dynamic>((value) => value);
final futureThenInferred = () => _future.then((value) => value);
final futureThenValue = () => _future.then((value) => _value);
final futureThenMappedIndex = () => _future.then((value) => _items[0]);
final futureThenMapLookup = () => _future.then((value) => _map[value]);
final futureCatchError = () => _future.catchError((Object error) => _value);
final futureWhenComplete = () => _future.whenComplete(() {});
final futureWhenCompleteDynamic = () => _future.whenComplete(() => _value);
final futureTimeout = () => _future.timeout(Duration.zero);
final futureTimeoutFallback = () => _future.timeout(Duration.zero, onTimeout: () => _value);
final futureAsStreamDirect = () => _future.asStream();
final futureSync = () => Future.sync(() => _value);
final futureMicrotask = () => Future.microtask(() => _value);
final futureDelayed = () => Future.delayed(Duration.zero, () => _value);
final futureAny = () => Future.any<dynamic>(_futures);
final futureWait = () => Future.wait<dynamic>(_futures);
final futureError = () => Future.error(Object());
final futureSyncIndex = () => Future.sync(() => _items[0]);
final futureDelayedLookup = () => Future.delayed(Duration.zero, () => _map[_value]);
final futureWaitEager = () => Future.wait<dynamic>(_futures, eagerError: true);
final futureThenThen = () => _future.then((value) => value).then((value) => value);
final futureThenAsStreamFirst = () => _future.then((value) => value).asStream().first;
final futureThenCatchError = () => _future.then((value) => value).catchError((Object error) => _value);
final futureThenTimeout = () => _future.then((value) => value).timeout(Duration.zero);
final futureThenWhenComplete = () => _future.then((value) => value).whenComplete(() {});
final whereTypeInferred = () => _iterable.whereType();
final whereTypeDynamic = () => _iterable.whereType<dynamic>();
final reduceDynamic = () => _iterable.reduce((left, right) => left);
final foldDynamic = () => _iterable.fold<dynamic>(0, (previous, value) => value);
final iterableIndexed = () => _iterable.indexed;
final listAsMapValue = () => _items.asMap().values.first;
final listFrom = () => List.from(_items);
final listOf = () => List.of(_items);
final listUnmodifiable = () => List.unmodifiable(_items);
final listGenerate = () => List.generate(1, (_) => _value);
final listFilled = () => List.filled(1, _value);
final listEmpty = () => List.empty();
final setFrom = () => Set.from(_items);
final setOf = () => Set.of(_iterable);
final setUnmodifiable = () => Set.unmodifiable(_items);
final setIdentity = () => Set.identity();
final setLookup = () => _dynamicSet.lookup(_value);
final setUnion = () => _dynamicSet.union(<dynamic>{});
final setIntersection = () => _dynamicSet.intersection(<dynamic>{});
final setDifference = () => _dynamicSet.difference(<dynamic>{});
final iterableGenerate = () => Iterable.generate(1, (_) => _value);
final iterableEmpty = () => Iterable.empty();
final listFromIterable = () => List.from(_iterable, growable: false);
final setFromIterable = () => Set.from(_iterable);
final listGenerateConditional = () => List.generate(2, (index) => index == 0 ? _value : null);
final mapMap = () => _map.map((key, value) => MapEntry(key, value));
final mapMapExplicit = () => _map.map<dynamic, dynamic>((key, value) => MapEntry(key, value));
final mapMapKeyDynamic = () => _map.map<dynamic, String>((key, value) => MapEntry(key, value.toString()));
final mapMapValueDynamic = () => _map.map<String, dynamic>((key, value) => MapEntry(key.toString(), value));
final mapFrom = () => Map.from(_map);
final mapOf = () => Map.of(_map);
final mapUnmodifiable = () => Map.unmodifiable(_map);
final mapIdentity = () => Map.identity();
final mapFromEntries = () => Map.fromEntries(_map.entries);
final mapFromIterable = () => Map.fromIterable(_iterable, key: (element) => element, value: (element) => element);
final mapFromIterables = () => Map.fromIterables(_iterable, _iterable);
final mapStringKeyDynamicValue = () => Map.fromIterable(_iterable, key: (element) => 'key', value: (element) => element);
final mapDynamicKeyIntValue = () => Map.fromIterable(_iterable, key: (element) => element, value: (element) => 1);
final dynamicMapEntry = () => MapEntry(_value, _value);
final dynamicMapEntryKey = () => MapEntry(_value, 1).key;
final dynamicMapEntryValue = () => MapEntry('key', _value).value;
final mappedEntriesDynamicKey = () => _map.map((key, value) => MapEntry(key, value)).entries.first.key;
final mappedValuesDynamic = () => _map.map((key, value) => MapEntry(key, value)).values.first;
final mapMapCascade = () => _map.map((key, value) => MapEntry(key, value))..addAll(_map);
final mapUnmodifiableFromEntries = () => Map.unmodifiable(Map.fromEntries(_map.entries));
